CC = clang-9
AS = nasm
LD = ld
CFLAGS = \
	-fno-pic \
	-static \
	-fno-builtin \
	-fno-strict-aliasing \
	-fno-omit-frame-pointer  \
	-fno-stack-protector  \
	-O2 -Wall -ggdb -Werror
# -fno-pic 		= disable position-independent code
# -static		= link statically
# -fno-builtin	= don't recognise builtin functions
# -fno-omit-frame-pointer = don't optimise away rbp usage
# -fno-stack-protector = don't include code protecting from buffer overflow


